[package]
name = "icrc3.mo"
version = "0.1.0"
description = "icrc3 for motoko"
repository = ""
keywords = [ "ledger", "transactions", "log" ]
license = "MIT"

[dependencies]
base = "https://github.com/dfinity/motoko-base#moc-0.10.1@80ededb39954739b18b88fc0e5561264003cf9ab"
stable-write-only = "https://github.com/skilesare/StableWriteOnly.mo#v0.1.0@02e9aac74bdbed86b52ebed985d82b6ef66a76d8"
map9 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1@10b68f6ea8df5e72dfa4c07a50c8bb60a916c233"
vector = "0.2.0"
sha2 = "0.0.4"
rep-indy-hash = "0.1.1"
cert = "https://github.com/nomeata/ic-certification#v0.1.3@c403ffec0a60f658a1009976c785aa567ff0da77"

[dev-dependencies]
test = "1.1.1"
fuzz = "0.1.2"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"